server:
  port: 8091

spring:
  data:
    mongodb:
     # uri: mongodb+srv://Khome:Danny006@cluster0.mn8b9xh.mongodb.net/emergencydb?retryWrites=true&w=majority&appName=Cluster0
      uri: mongodb+srv://NodStan:Stanleyobi123!@cluster0.q5hehu2.mongodb.net/userHealthhub?retryWrites=true&w=majority&appName=Cluster0
